# <center> <h1>Assignment 2</h1> </center>
<center> <h1>EIN 4933/6935 Python for Data Science Summer 2020</h1> </center>

## Part 1
The following code loads a popular dataset so-called titanic.csv from an online repository into a dataframe named "titanic". As you may guess, this is a real data set that stores some important information about the passengers of Titanic. 

The columns are organized as "PassengerId", "Survived", "Pclass", "Name", "Sex", "Age", "SibSp", "Parch", "Ticket", "Fare", "Cabin", "Embarked". The column named "Survived" shows whether a passenger survided (with 1) or not (with 0) from this tragic accident. Use this dataset to answer the questions below. You can create as many cells as you desire for all solutions.<br/>


In [24]:
import pandas as pd

In [1]:
import pandas as pd
# titanic = pd.read_csv("https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv")
titanic = pd.read_csv("https://sites.google.com/site/yasinunlu/home/research/new1/Titanic_train.csv")
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [10]:
df = titanic.copy()

In [44]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### Question 1:
Write a function named "data_preprocessing" that accepts the dataset in dataframe as only argument and does the following tasks and returns the updated dataframe:<br/>
0) Drop "PassengerId" and "Ticket" columns from the dataframe.<br/>
1) Check if there are any rows that have missing entries for all columns.<br/> 
2) Remove such rows from the given dataset.<br/>
3) Convert the data type of "Fare" and "Age" to int.<br/>
4) Rename "SibSp" as "Siblings/Spouses Aboard", and "Parch" as "Parents/Children Aboard".<br/>
5) Under column "Name": replace 'Mlle' with 'Miss', replace 'Ms' with 'Miss' and replace 'Mme'with 'Mrs'.<br/>

In [12]:
# 0) Drop "PassengerId" and "Ticket" columns from the dataframe.
df.drop(labels=["PassengerId", "Ticket"], axis=1, inplace=True)

In [55]:
df.loc[891] = float('nan') # none in df so add a nan row to test and remove

In [56]:
# 1) Check if there are any rows that have missing entries for all columns.
# 2) Remove such rows from the given dataset.
nan_rows = []
for i in range(len(df['Name'])):
    if df.iloc[i].isna().all():
        nan_rows.append(i)
print("Full NaN rows removed:", nan_rows)

Full NaN rows removed: [891]


In [57]:
df.drop(labels=nan_rows, axis=0, inplace=True)
print(f"The DataFrame now contains {len(df)} rows.")

The DataFrame now contains 891 rows.


In [16]:
# 3) Convert the data type of "Fare" and "Age" to int.

In [94]:
infants = df[(df["Age"]<1)]  # check how infants are recorded
infants

Survived  Pclass                             Name     Sex   Age  SibSp  \
78        1.0     2.0    Caldwell, Master. Alden Gates    male  0.83    0.0   
305       1.0     1.0   Allison, Master. Hudson Trevor    male  0.92    1.0   
469       1.0     3.0    Baclini, Miss. Helene Barbara  female  0.75    2.0   
644       1.0     3.0           Baclini, Miss. Eugenie  female  0.75    2.0   
755       1.0     2.0        Hamalainen, Master. Viljo    male  0.67    1.0   
803       1.0     3.0  Thomas, Master. Assad Alexander    male  0.42    0.0   
831       1.0     2.0  Richards, Master. George Sibley    male  0.83    1.0   

     Parch      Fare    Cabin Embarked  
78     2.0   29.0000      NaN        S  
305    2.0  151.5500  C22 C26        S  
469    1.0   19.2583      NaN        C  
644    1.0   19.2583      NaN        C  
755    1.0   14.5000      NaN        S  
803    1.0    8.5167      NaN        C  
831    1.0   18.7500      NaN        S

In [95]:
infants['Age_int'] = infants['Age'].astype(int) # create a new col with Age converted to int

C:\Users\nvanb\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [96]:
infants

Survived  Pclass                             Name     Sex   Age  SibSp  \
78        1.0     2.0    Caldwell, Master. Alden Gates    male  0.83    0.0   
305       1.0     1.0   Allison, Master. Hudson Trevor    male  0.92    1.0   
469       1.0     3.0    Baclini, Miss. Helene Barbara  female  0.75    2.0   
644       1.0     3.0           Baclini, Miss. Eugenie  female  0.75    2.0   
755       1.0     2.0        Hamalainen, Master. Viljo    male  0.67    1.0   
803       1.0     3.0  Thomas, Master. Assad Alexander    male  0.42    0.0   
831       1.0     2.0  Richards, Master. George Sibley    male  0.83    1.0   

     Parch      Fare    Cabin Embarked  Age_int  
78     2.0   29.0000      NaN        S        0  
305    2.0  151.5500  C22 C26        S        0  
469    1.0   19.2583      NaN        C        0  
644    1.0   19.2583      NaN        C        0  
755    1.0   14.5000      NaN        S        0  
803    1.0    8.5167      NaN        C        0  
831    1.0   18.7500      NaN        S        0

### Note on type conversion

Apparently converting from `float` to `int` truncates the float and does not round the value (i.e. all values below `1.0` are truncated to `0` even `0.9` will become `0`). Therefore converting all `NaN` values to 0 first is not a good idea. 

* Perhaps round the numbers first?
    - this will help all values greater than 0.5, but we would lose age data for any babies less than a year old (only one in the is data set but it still could be a problem)
* Change `NaN` values to -1 or -99?
    - this could work and would distinguish the old nan values, but it could be confusing and may cause problems if try to do arithmetic (i.e. `sum()`) on the column values
* use the `.astype` argument `errors='ignore'` 
    - this will keep `NaN` values as `NaN` but the series/df won't be converted to `int`. It will still be of type `float64`!
    

In [85]:
infant_index = list(infants.index)
infant_index

[78, 305, 469, 644, 755, 803, 831]

In [128]:
df['Age'].isna().sum()  # how many nan values in Age col? - 177

177

In [129]:
df['Fare'].isna().any()  # are any nan values in Fare col? - No

False

In [114]:
# titanic["Age"] = titanic["Age"].fillna(0) #first takes care of NAs. Fill with 0s.
# titanic["Age"] = titanic["Age"].astype(int)
age_int = df[['Age']].astype(int, errors='ignore')  # keeping nan values keeps type float
age_int['Fare'] = df['Fare']
age_int

Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [115]:
age_int.info()  # 

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Age     714 non-null    float64
 1   Fare    891 non-null    float64
dtypes: float64(2)
memory usage: 20.9 KB


In [117]:
age_int.fillna({'Age':-99, 'Fare':-99}, inplace=True)

In [118]:
age_int

Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888 -99.0  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [130]:
age_int['Age'] = age_int['Age'].astype(int)
age_int['Fare'] = age_int['Fare'].astype(int)

In [131]:
age_int.info()  # make sure converted to int

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     891 non-null    int32
 1   Fare    891 non-null    int32
dtypes: int32(2)
memory usage: 13.9 KB


In [136]:
print("Data type of 'Age':", age_int['Age'].dtypes)
print("Data type of 'Fare':", age_int['Fare'].dtypes)

Data type of 'Age': int32


In [17]:
# 4) Rename "SibSp" as "Siblings/Spouses Aboard", and "Parch" as "Parents/Children Aboard".

In [209]:
df.rename(columns={"SibSp":"Siblings/Spouses Aboard", "Parch":"Parents/Children Aboard"}, inplace=True)

In [210]:
df

Survived  Pclass                                               Name  \
0         0.0     3.0                            Braund, Mr. Owen Harris   
1         1.0     1.0  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1.0     3.0                             Heikkinen, Miss. Laina   
3         1.0     1.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0.0     3.0                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
886       0.0     2.0                              Montvila, Rev. Juozas   
887       1.0     1.0                       Graham, Miss. Margaret Edith   
888       0.0     3.0           Johnston, Miss. Catherine Helen "Carrie"   
889       1.0     1.0                              Behr, Mr. Karl Howell   
890       0.0     3.0                                Dooley, Mr. Patrick   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  \
0      male  22.0                      1.0                      0.0   7.2500   
1    female  38.0                      1.0                      0.0  71.2833   
2    female  26.0                      0.0                      0.0   7.9250   
3    female  35.0                      1.0                      0.0  53.1000   
4      male  35.0                      0.0                      0.0   8.0500   
..      ...   ...                      ...                      ...      ...   
886    male  27.0                      0.0                      0.0  13.0000   
887  female  19.0                      0.0                      0.0  30.0000   
888  female   NaN                      1.0                      2.0  23.4500   
889    male  26.0                      0.0                      0.0  30.0000   
890    male  32.0                      0.0                      0.0   7.7500   

    Cabin Embarked  
0     NaN        S  
1     C85        C  
2     NaN        S  
3    C123        S  
4     NaN        S  
..    ...      ...  
886   NaN        S  
887   B42        S  
888   NaN        S  
889  C148        C  
890   NaN        Q  

[891 rows x 10 columns]

In [204]:
# 5) Under column "Name": replace 'Mlle' with 'Miss', replace 'Ms' with 'Miss' and replace 'Mme'with 'Mrs'.

# df[['Name']].applymap(lambda x: x.replace(" ", "")) #remove white space from a string
# df.replace({'Name': {'Mlle':'Miss', 'Ms':'Miss', 'Mme':'Mrs'}})
# df[['Name']].applymap(lambda x: x.replace({'Name': {'Mr.':'MALE', 'Mrs':'FEMALE', 'Miss':'YOUNG FEMALE'}},None))
# df[['Name']].applymap(lambda x: x.replace('Mr','MALE'))
# df.replace({'Name': {'Mr.':'MALE', 'Mrs':'FEMALE', 'Miss':'YOUNG FEMALE'}}) # doesn't work because looking at whole object 
#     # need regex for above
# df.replace({'Pclass': {3.0:3.33, 1.0:1.11, 2.0:2.22}})  # this WORKS! 
# df[['Name']].applymap(lambda x: x.replace('Mr','MALE'))  # this also works!!
df['Name'] = df[['Name']].applymap(lambda x: x.replace('Mlle','Miss')) 
df['Name'] = df[['Name']].applymap(lambda x: x.replace('Ms','Miss'))
df['Name'] = df[['Name']].applymap(lambda x: x.replace('Mme','Mrs'))

In [202]:
df.loc[[369, 443, 641, 710]]  # look at rows before make name changes

Survived  Pclass                                              Name  \
369       1.0     1.0                     Aubart, Mme. Leontine Pauline   
443       1.0     2.0                         Reynaldo, Ms. Encarnacion   
641       1.0     1.0                              Sagesser, Mlle. Emma   
710       1.0     1.0  Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")   

        Sex   Age  SibSp  Parch     Fare Cabin Embarked  
369  female  24.0    0.0    0.0  69.3000   B35        C  
443  female  28.0    0.0    0.0  13.0000   NaN        S  
641  female  24.0    0.0    0.0  69.3000   B35        C  
710  female  24.0    0.0    0.0  49.5042   C90        C

In [205]:
df.loc[prefixes]  # note: run AFTER cells below to make sure name changes worked

Survived  Pclass                                              Name  \
369       1.0     1.0                     Aubart, Mrs. Leontine Pauline   
443       1.0     2.0                       Reynaldo, Miss. Encarnacion   
641       1.0     1.0                              Sagesser, Miss. Emma   
710       1.0     1.0  Mayne, Miss. Berthe Antonine ("Mrs de Villiers")   

        Sex   Age  SibSp  Parch     Fare Cabin Embarked  
369  female  24.0    0.0    0.0  69.3000   B35        C  
443  female  28.0    0.0    0.0  13.0000   NaN        S  
641  female  24.0    0.0    0.0  69.3000   B35        C  
710  female  24.0    0.0    0.0  49.5042   C90        C

In [168]:
female = df[df['Sex']=='female'] # make new col for females only
female

Survived  Pclass                                               Name  \
1         1.0     1.0  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1.0     3.0                             Heikkinen, Miss. Laina   
3         1.0     1.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
8         1.0     3.0  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   
9         1.0     2.0                Nasser, Mrs. Nicholas (Adele Achem)   
..        ...     ...                                                ...   
880       1.0     2.0       Shelley, Mrs. William (Imanita Parrish Hall)   
882       0.0     3.0                       Dahlberg, Miss. Gerda Ulrika   
885       0.0     3.0               Rice, Mrs. William (Margaret Norton)   
887       1.0     1.0                       Graham, Miss. Margaret Edith   
888       0.0     3.0           Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch     Fare Cabin Embarked  
1    female  38.0    1.0    0.0  71.2833   C85        C  
2    female  26.0    0.0    0.0   7.9250   NaN        S  
3    female  35.0    1.0    0.0  53.1000  C123        S  
8    female  27.0    0.0    2.0  11.1333   NaN        S  
9    female  14.0    1.0    0.0  30.0708   NaN        C  
..      ...   ...    ...    ...      ...   ...      ...  
880  female  25.0    0.0    1.0  26.0000   NaN        S  
882  female  22.0    0.0    0.0  10.5167   NaN        S  
885  female  39.0    0.0    5.0  29.1250   NaN        Q  
887  female  19.0    0.0    0.0  30.0000   B42        S  
888  female   NaN    1.0    2.0  23.4500   NaN        S  

[314 rows x 10 columns]

In [172]:
female['Name'][888].split()

['Johnston,', 'Miss.', 'Catherine', 'Helen', '"Carrie"']

In [184]:
female.reset_index(inplace=True) # need to reset the index b/c slice not sequential for iterating below
female  # note 'level_0' just b/c I ran this cell (reset index) twice

level_0  index  Survived  Pclass  \
0          0      1       1.0     1.0   
1          1      2       1.0     3.0   
2          2      3       1.0     1.0   
3          3      8       1.0     3.0   
4          4      9       1.0     2.0   
..       ...    ...       ...     ...   
309      309    880       1.0     2.0   
310      310    882       0.0     3.0   
311      311    885       0.0     3.0   
312      312    887       1.0     1.0   
313      313    888       0.0     3.0   

                                                  Name     Sex   Age  SibSp  \
0    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
1                               Heikkinen, Miss. Laina  female  26.0    0.0   
2         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
3    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0    0.0   
4                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0    1.0   
..                                                 ...     ...   ...    ...   
309       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0    0.0   
310                       Dahlberg, Miss. Gerda Ulrika  female  22.0    0.0   
311               Rice, Mrs. William (Margaret Norton)  female  39.0    0.0   
312                       Graham, Miss. Margaret Edith  female  19.0    0.0   
313           Johnston, Miss. Catherine Helen "Carrie"  female   NaN    1.0   

     Parch     Fare Cabin Embarked  
0      0.0  71.2833   C85        C  
1      0.0   7.9250   NaN        S  
2      0.0  53.1000  C123        S  
3      2.0  11.1333   NaN        S  
4      0.0  30.0708   NaN        C  
..     ...      ...   ...      ...  
309    1.0  26.0000   NaN        S  
310    0.0  10.5167   NaN        S  
311    5.0  29.1250   NaN        Q  
312    0.0  30.0000   B42        S  
313    2.0  23.4500   NaN        S  

[314 rows x 12 columns]

In [219]:
idx = []
for i in range(len(female['Name'])):
    L = female['Name'][i].split()
    if 'Mlle.' in L: #['Mlle.','Ms.','Mme.']
        idx.append(i)
    elif "Ms." in L:
        idx.append(i)
    elif "Mme." in L:
        idx.append(i)
idx

[140, 170, 235, 255]

In [195]:
female.iloc[idx] # note idx is new index after reset_index

level_0  index  Survived  Pclass  \
140      140    369       1.0     1.0   
170      170    443       1.0     2.0   
235      235    641       1.0     1.0   
255      255    710       1.0     1.0   

                                                 Name     Sex   Age  SibSp  \
140                     Aubart, Mme. Leontine Pauline  female  24.0    0.0   
170                         Reynaldo, Ms. Encarnacion  female  28.0    0.0   
235                              Sagesser, Mlle. Emma  female  24.0    0.0   
255  Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")  female  24.0    0.0   

     Parch     Fare Cabin Embarked  
140    0.0  69.3000   B35        C  
170    0.0  13.0000   NaN        S  
235    0.0  69.3000   B35        C  
255    0.0  49.5042   C90        C

In [200]:
prefixes = list(female.iloc[idx]['index']) # make a list of old indicies from original df
prefixes

[369, 443, 641, 710]

In [ ]:
#Work on your solution here and after. 
#make sure to follow the given structure below

#1) Write your function here
def data_preprocessing (df=titanic):
    """Write a function named "data_preprocessing" that accepts the dataset in dataframe as only argument and does the following tasks and returns the updated dataframe:
    0) Drop "PassengerId" and "Ticket" columns from the dataframe.
    1) Check if there are any rows that have missing entries for all columns.
    2) Remove such rows from the given dataset.
    3) Convert the data type of "Fare" and "Age" to int.
    4) Rename "SibSp" as "Siblings/Spouses Aboard", and "Parch" as "Parents/Children Aboard".
    5) Under column "Name": replace 'Mlle' with 'Miss', replace 'Ms' with 'Miss' and replace 'Mme'with 'Mrs'."""
    
    # 0) Drop "PassengerId" and "Ticket" columns from the dataframe.
    df.drop(labels=["PassengerId", "Ticket"], axis=1, inplace=True)
    
    # 1) Check if there are any rows that have missing entries for all columns.
    # 2) Remove such rows from the given dataset.
    nan_rows = []
    for i in range(len(df['Name'])):
        if df.iloc[i].isna().all():
            nan_rows.append(i)
    print("Full NaN rows removed:", nan_rows)
    df.drop(labels=nan_rows, axis=0, inplace=True)
    print(f"The DataFrame now contains {len(df)} rows.")
    
    #3) Convert the data type of "Fare" and "Age" to int.
    df.fillna({'Age':-99, 'Fare':-99}, inplace=True)
    df['Age'] = df['Age'].astype(int)
    df['Fare'] = df['Fare'].astype(int)
    print("Data type of 'Age':", df['Age'].dtypes)
    print("Data type of 'Fare':", df['Fare'].dtypes)
    
    # 4) Rename "SibSp" as "Siblings/Spouses Aboard", and "Parch" as "Parents/Children Aboard".
    df.rename(columns={"SibSp":"Siblings/Spouses Aboard", "Parch":"Parents/Children Aboard"}, inplace=True)
    
    # 5) Under column "Name": replace 'Mlle' with 'Miss', replace 'Ms' with 'Miss' and replace 'Mme'with 'Mrs'.
    df['Name'] = df[['Name']].applymap(lambda x: x.replace('Mlle','Miss')) 
    df['Name'] = df[['Name']].applymap(lambda x: x.replace('Ms','Miss'))
    df['Name'] = df[['Name']].applymap(lambda x: x.replace('Mme','Mrs'))
    return df

#2) Call your function here
new_titanic = data_preprocessing(titanic)
new_titanic.head()
new_titanic.loc[[369, 443, 641, 710]]

## Question 2:
We are interested in adding new columns which are so-called features.<br/>
Create a new function called "feature_extraction" which does the following updates to the existing dataframe.<br/>
In short, we will fully change the columns "Name", "Embarked", "Sex", "Cabin" and "Age" into numeric.

1. Name column should be of int type.  For those titles in name column, this column should indicate 1 for  "Mr."; 2 for "Miss."; 3 for "Mrs."; 4 for "Master."; 5 for "Rare" and 0 for any others.  
2. Convert "Embarked" column into numeric. Replace "S" with 0; replace "C" with 1 and replace "Q" with 2. For the missing ones (if any), just fill with the most common one.  
3. Convert "Sex" column into numeric.Replace "male" with 0 and replace "female" with 1. For the missing ones (if any), just fill with the most common one.  
4. The column named "Cabin" includes strings with letters and numbers, for example "C85" and the letter refers to the cabin group. This column should indicate integer value of 1 for cabin name starts with letter "A". The rest of the numbers should appear according this dictionary: {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6, "G": 7, "U": 8}. Any missing entries should be replaced with 0.  
5. Fill missing values from "Age" column according to the following ad-hoc imputation technique: A random integer withdrawn from the set (mean - standard deviation, mean + standard deviation).  
6. Any missing values from "Fare" column should be replaced with 0.  
7. Update "Fare" column according to the following:  
    * if 0 <= 'Fare' < 10, then 'Fare' = 0<br/>
    * if 10 <= 'Fare' < 20, then 'Fare' = 1<br/>
    * if 20 <= 'Fare' < 30, then 'Fare' = 2<br/>
    * if 30 <= 'Fare' < 100, then 'Fare' = 3<br/>
    * if 100 <= 'Fare' < 200, then 'Fare' = 4<br/>
    * if 200 <= 'Fare' then 'Fare' = 5<br/>
8. Update "Age" column according to the following:
   * if 'Age' <= 10, then 'Age' = 0
   * if 'Age' > 10 & 'Age' <= 15 then 'Age' = 1
   * if 'Age' > 15 & 'Age' <= 20 then 'Age' = 2
   * if 'Age' > 20 & 'Age' <= 25 then 'Age' = 3
   * if 'Age' > 25 & 'Age' <= 35 then 'Age' = 4
   * if 'Age' > 35 & 'Age' <= 40 then 'Age' = 5
   * if 'Age' > 40 & 'Age' <= 60 then 'Age' = 6
   * if 'Age' > 60 then 'Age' = 6


In [212]:
# 1. Name column should be of int type. For those titles in name column, this column should indicate:
# 1 for "Mr."; 2 for "Miss."; 3 for "Mrs."; 4 for "Master."; 5 for "Rare" and 0 for any others.
{"Mr.":1, "Miss.":2, "Mrs.":3, "Master.":4, "Rare":5} #, "others":0}


NameError: name 'others' is not defined

In [223]:
idx1 = []
for i in range(len(df['Name'])):
    L = df['Name'][i].split()
    if 'Mr.' in L: #['Mlle.','Ms.','Mme.']
        idx1.append(i)
    elif "Master." in L:
        idx1.append(i)
    elif "Miss." in L:
        idx1.append(i)
    elif "Mrs." in L:
        idx1.append(i)
len(idx1)

868

In [227]:
rare = []
for i in range(891):
    if i not in idx1:
        rare.append(i)
rare

[30,
 149,
 150,
 245,
 249,
 317,
 398,
 449,
 536,
 556,
 599,
 626,
 632,
 647,
 660,
 694,
 745,
 759,
 766,
 796,
 822,
 848,
 886]

In [228]:
df.loc[rare]

Survived  Pclass                                               Name  \
30        0.0     1.0                           Uruchurtu, Don. Manuel E   
149       0.0     2.0                  Byles, Rev. Thomas Roussel Davids   
150       0.0     2.0                         Bateman, Rev. Robert James   
245       0.0     1.0                        Minahan, Dr. William Edward   
249       0.0     2.0                      Carter, Rev. Ernest Courtenay   
317       0.0     2.0                               Moraweck, Dr. Ernest   
398       0.0     2.0                                   Pain, Dr. Alfred   
449       1.0     1.0                     Peuchen, Major. Arthur Godfrey   
536       0.0     1.0                  Butt, Major. Archibald Willingham   
556       1.0     1.0  Duff Gordon, Lady. (Lucille Christiana Sutherl...   
599       1.0     1.0       Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")   
626       0.0     2.0                     Kirkland, Rev. Charles Leonard   
632       1.0     1.0                          Stahelin-Maeglin, Dr. Max   
647       1.0     1.0                Simonius-Blumer, Col. Oberst Alfons   
660       1.0     1.0                      Frauenthal, Dr. Henry William   
694       0.0     1.0                                    Weir, Col. John   
745       0.0     1.0                       Crosby, Capt. Edward Gifford   
759       1.0     1.0  Rothes, the Countess. of (Lucy Noel Martha Dye...   
766       0.0     1.0                          Brewe, Dr. Arthur Jackson   
796       1.0     1.0                        Leader, Dr. Alice (Farnham)   
822       0.0     1.0                    Reuchlin, Jonkheer. John George   
848       0.0     2.0                                  Harper, Rev. John   
886       0.0     2.0                              Montvila, Rev. Juozas   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard      Fare  \
30     male  40.0                      0.0                      0.0   27.7208   
149    male  42.0                      0.0                      0.0   13.0000   
150    male  51.0                      0.0                      0.0   12.5250   
245    male  44.0                      2.0                      0.0   90.0000   
249    male  54.0                      1.0                      0.0   26.0000   
317    male  54.0                      0.0                      0.0   14.0000   
398    male  23.0                      0.0                      0.0   10.5000   
449    male  52.0                      0.0                      0.0   30.5000   
536    male  45.0                      0.0                      0.0   26.5500   
556  female  48.0                      1.0                      0.0   39.6000   
599    male  49.0                      1.0                      0.0   56.9292   
626    male  57.0                      0.0                      0.0   12.3500   
632    male  32.0                      0.0                      0.0   30.5000   
647    male  56.0                      0.0                      0.0   35.5000   
660    male  50.0                      2.0                      0.0  133.6500   
694    male  60.0                      0.0                      0.0   26.5500   
745    male  70.0                      1.0                      1.0   71.0000   
759  female  33.0                      0.0                      0.0   86.5000   
766    male   NaN                      0.0                      0.0   39.6000   
796  female  49.0                      0.0                      0.0   25.9292   
822    male  38.0                      0.0                      0.0    0.0000   
848    male  28.0                      0.0                      1.0   33.0000   
886    male  27.0                      0.0                      0.0   13.0000   

    Cabin Embarked  
30    NaN        C  
149   NaN        S  
150   NaN        S  
245   C78        Q  
249   NaN        S  
317   NaN        S  
398   NaN        S  
449  C104        S  
536   B38        S  
556   A16        C  
599 

I Propose adding groups for "Rev.", "Dr.", "Military" and "Nobility"

In [213]:
df['Name'].map()

Survived  Pclass                                               Name  \
0         0.0     3.0                            Braund, Mr. Owen Harris   
1         1.0     1.0  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1.0     3.0                             Heikkinen, Miss. Laina   
3         1.0     1.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0.0     3.0                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
886       0.0     2.0                              Montvila, Rev. Juozas   
887       1.0     1.0                       Graham, Miss. Margaret Edith   
888       0.0     3.0           Johnston, Miss. Catherine Helen "Carrie"   
889       1.0     1.0                              Behr, Mr. Karl Howell   
890       0.0     3.0                                Dooley, Mr. Patrick   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  \
0      male  22.0                      1.0                      0.0   7.2500   
1    female  38.0                      1.0                      0.0  71.2833   
2    female  26.0                      0.0                      0.0   7.9250   
3    female  35.0                      1.0                      0.0  53.1000   
4      male  35.0                      0.0                      0.0   8.0500   
..      ...   ...                      ...                      ...      ...   
886    male  27.0                      0.0                      0.0  13.0000   
887  female  19.0                      0.0                      0.0  30.0000   
888  female   NaN                      1.0                      2.0  23.4500   
889    male  26.0                      0.0                      0.0  30.0000   
890    male  32.0                      0.0                      0.0   7.7500   

    Cabin Embarked  
0     NaN        S  
1     C85        C  
2     NaN        S  
3    C123        S  
4     NaN        S  
..    ...      ...  
886   NaN        S  
887   B42        S  
888   NaN        S  
889  C148        C  
890   NaN        Q  

[891 rows x 10 columns]

In [ ]:
#Work on your solution here and after. 
#1) Write your function here
def feature_extraction (args):
    #body of the function
    return df

#2) Call your function here
new_titanic = feature_extraction(new_titanic)
new_titanic.head()

## Part 2
The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

In [229]:
import pandas as pd
census_df = pd.read_csv('https://sites.google.com/site/yasinunlu/home/research/new1/census.csv')
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  RDOMESTICMIG2011  \
0        4779736            4780127          4785161  ...          0.002295   
1          54571              54571            54660  ...          7.242091   
2         182265             182265           183193  ...         14.832960   
3          27457              27457            27341  ...         -4.728132   
4          22915              22919            22861  ...         -5.527043   

   RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  RDOMESTICMIG2015  \
0         -0.193196          0.381066          0.582002         -0.467369   
1         -2.915927         -3.012349          2.265971         -2.530799   
2         17.647293         21.845705         19.243286         17.197872   
3         -2.500690         -7.056824         -3.904217        -10.543299   
4         -5.068871         -6.201001         -0.177537          0.177258   

   RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015  
0     1.030015     0.826644     1.383282     1.724718     0.712594  
1     7.606016    -2.626146    -2.722002     2.592270    -2.187333  
2    15.844176    18.559627    22.727626    20.317142    18.293499  
3    -4.874741    -2.758113    -7.167664    -3.978583   -10.543299  
4    -5.088389    -4.363636    -5.403729     0.754533     1.107861  

[5 rows x 100 columns]

### Question 1
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [230]:
# SUMLEV = 40 --> State
# SUMLEV = 50 --> County
census_df['SUMLEV'].unique()

array([40, 50], dtype=int64)

In [232]:
len(census_df)

3193

In [233]:
counties = census_df[census_df['SUMLEV'] == 50]

In [242]:
counties.groupby("STNAME").count()['COUNTY'].idxmax()

'Texas'

In [238]:
counties.groupby("STNAME").count().sort_values("SUMLEV", axis=0, ascending=False)

SUMLEV  REGION  DIVISION  STATE  COUNTY  CTYNAME  \
STNAME                                                                   
Texas                    254     254       254    254     254      254   
Georgia                  159     159       159    159     159      159   
Virginia                 133     133       133    133     133      133   
Kentucky                 120     120       120    120     120      120   
Missouri                 115     115       115    115     115      115   
Kansas                   105     105       105    105     105      105   
Illinois                 102     102       102    102     102      102   
North Carolina           100     100       100    100     100      100   
Iowa                      99      99        99     99      99       99   
Tennessee                 95      95        95     95      95       95   
Nebraska                  93      93        93     93      93       93   
Indiana                   92      92        92     92      92       92   
Ohio                      88      88        88     88      88       88   
Minnesota                 87      87        87     87      87       87   
Michigan                  83      83        83     83      83       83   
Mississippi               82      82        82     82      82       82   
Oklahoma                  77      77        77     77      77       77   
Arkansas                  75      75        75     75      75       75   
Wisconsin                 72      72        72     72      72       72   
Pennsylvania              67      67        67     67      67       67   
Alabama                   67      67        67     67      67       67   
Florida                   67      67        67     67      67       67   
South Dakota              66      66        66     66      66       66   
Colorado                  64      64        64     64      64       64   
Louisiana                 64      64        64     64      64       64   
New York                  62      62        62     62      62       62   
California                58      58        58     58      58       58   
Montana                   56      56        56     56      56       56   
West Virginia             55      55        55     55      55       55   
North Dakota              53      53        53     53      53       53   
South Carolina            46      46        46     46      46       46   
Idaho                     44      44        44     44      44       44   
Washington                39      39        39     39      39       39   
Oregon                    36      36        36     36      36       36   
New Mexico                33      33        33     33      33       33   
Alaska                    29      29        29     29      29       29   
Utah                      29      29        29     29      29       29   
Maryland                  24      24        24     24      24       24   
Wyoming                   23      23        23     23      23       23   
New Jersey                21      21        21     21      21       21   
Nevada                    17      17        17     17      17       17   
Maine                     16      16        16     16      16       16   
Arizona                   15      15        15     15      15       15   
Vermont                   14      14        14     14      14       14   
Massachusetts             14      14        14     14      14       14   
New Hampshire             10      10        10     10      10       10   
Connecticut                8       8         8      8       8        8   
Rhode Island               5       5         5      5       5        5   
Hawaii                     5       5         5      5       5        5   
Delaware                   3       3         3      3       3        3   
District of Columbia       1       1         1      1       1        1   

                      CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
STNAME                  

### Question 2
Only looking at the three most populous counties for each state, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [248]:
states = census_df[census_df['SUMLEV'] == 40] # create new df with only states
list(states.sort_values('CENSUS2010POP',ascending = False).head(3)['STNAME'])  # CA, TX, and NY

['California', 'Texas', 'New York']

In [255]:
counties.groupby('STNAME')['CENSUS2010POP'].nlargest(3)

STNAME         
Alabama    37      658466
           49      412992
           45      334811
Alaska     71      291826
           76       97581
                    ...  
Wisconsin  3109    488073
           3164    389891
Wyoming    3180     91738
           3182     75450
           3172     46133
Name: CENSUS2010POP, Length: 151, dtype: int64

In [261]:
top3 = counties.groupby('STNAME')['CENSUS2010POP'].nlargest(3).index
top3

MultiIndex([(      'Alabama',   37),
            (      'Alabama',   49),
            (      'Alabama',   45),
            (       'Alaska',   71),
            (       'Alaska',   76),
            (       'Alaska',   85),
            (      'Arizona',  106),
            (      'Arizona',  109),
            (      'Arizona',  110),
            (     'Arkansas',  174),
            ...
            (   'Washington', 3031),
            ('West Virginia', 3060),
            ('West Virginia', 3042),
            ('West Virginia', 3046),
            (    'Wisconsin', 3137),
            (    'Wisconsin', 3109),
            (    'Wisconsin', 3164),
            (      'Wyoming', 3180),
            (      'Wyoming', 3182),
            (      'Wyoming', 3172)],
           names=['STNAME', None], length=151)

In [263]:
top3_index = [i[1] for i in top3]

In [277]:
statepop_bytop3 = counties.loc[top3_index].groupby('STNAME').sum()
list(statepop_bytop3.sort_values('CENSUS2010POP',ascending = False).head(4).index)

['California', 'Texas', 'Illinois', 'New York']

### Note: 
when going just by the top 3 most populus counties in each state Illinois beats out New York

### Question 3
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

### Question 4
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [280]:
region12 = counties[(counties['REGION'] == 1) | (counties['REGION'] == 2)]

In [287]:
region12_pop = region12[counties['POPESTIMATE2015'] > counties['POPESTIMATE2014']].filter(['STNAME','CTYNAME'])
region12_pop

C:\Users\nvanb\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


STNAME             CTYNAME
315   Connecticut    Fairfield County
618      Illinois    Champaign County
625      Illinois     Crawford County
628      Illinois      De Witt County
633      Illinois    Effingham County
...           ...                 ...
3156    Wisconsin    Sheboygan County
3158    Wisconsin  Trempealeau County
3159    Wisconsin       Vernon County
3163    Wisconsin   Washington County
3164    Wisconsin     Waukesha County

[493 rows x 2 columns]

In [291]:
region12_index = list(region12_pop['CTYNAME'].index)

In [292]:
washington_index = []
for i in region12_index:
    L = region12_pop['CTYNAME'][i].split()
    if L[0] == "Washington":
        washington_index.append(i)
washington_index

[896, 1419, 2345, 2355, 3163]

In [295]:
washington_cty = region12_pop.loc[washington_index]
washington_cty

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [296]:
washington_cty.shape

(5, 2)

In [294]:
census_df.loc[washington_index]

SUMLEV  REGION  DIVISION  STATE  COUNTY        STNAME  \
896       50       2         4     19     183          Iowa   
1419      50       2         4     27     163     Minnesota   
2345      50       1         2     42     125  Pennsylvania   
2355      50       1         1     44       9  Rhode Island   
3163      50       2         3     55     131     Wisconsin   

                CTYNAME  CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
896   Washington County          21704              21704            21697   
1419  Washington County         238136             238134           238995   
2345  Washington County         207820             207820           207877   
2355  Washington County         126979             127094           127085   
3163  Washington County         131887             131885           131967   

      ...  RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  \
896   ...          5.743693          2.468684         -0.364282   
1419  ...          2.555118          3.260957          2.285952   
2345  ...          3.683135          3.260434          1.219337   
2355  ...         -4.669304         -2.659574          1.551904   
3163  ...         -0.794876          0.785279         -2.215465   

      RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
896           0.272171          1.849596     5.881542     2.560117   
1419          3.072543          0.678755     4.178076     4.907905   
2345          2.113561          1.656917     4.062988     3.750219   
2355          1.400112          0.506035    -3.533527    -1.788880   
3163          1.601149         -0.434498    -0.431504     1.162817   

      RNETMIG2013  RNETMIG2014  RNETMIG2015  
896     -0.273212     0.408256     1.984933  
1419     4.009584     5.040262     2.615204  
2345     1.742595     2.762039     2.305276  
2355     2.462459     2.428442     1.533918  
3163    -1.763330     2.104796     0.059931  

[5 rows x 100 columns]